#!/usr/bin/env bash
#
# <xbar.title>mactemp</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>@AUTHOR@</xbar.author>
# <xbar.author.github>@GITHUB@</xbar.author.github>
# <xbar.desc>Apple Silicon thermals: die/SSD/battery temperature plus macOS thermal pressure, with the process causing it. No sudo, no helper daemon.</xbar.desc>
# <xbar.dependencies>swift</xbar.dependencies>
# <xbar.abouturl>@ABOUTURL@</xbar.abouturl>
#
# Reads real hardware sensors through IOKit's HID event system. The sensor
# reader is Swift, embedded below, compiled once into ~/Library/Caches on first
# run and reused after that. Apple Silicon only.
#
# DO NOT EDIT THIS FILE — it is generated by dist.sh from mactemp.swift and
# plugin.template.sh. Edit those and re-run ./dist.sh.

set -u

CACHE="$HOME/Library/Caches/mactemp"
SRC_HASH="@SRC_HASH@"
BIN="$CACHE/mactemp-$SRC_HASH"
STATE="$CACHE/state"
BUILDING="$CACHE/building"
FAILED="$CACHE/build-failed"
mkdir -p "$CACHE"

# --- thresholds ---------------------------------------------------------------
# A fanless Mac is *designed* to run hot and clamp its own clocks, so temperature
# alone is not a warning signal. Sustained thermal pressure is, because that is
# macOS saying it is actively giving up speed.
PRESSURE_SAMPLES=10   # consecutive serious/critical samples before alerting
BATTERY_WARN=45       # deg C; sustained heat here has a real lifespan cost
BATTERY_SAMPLES=10
NOTIFY_COOLDOWN=1800  # seconds between repeat notifications

# Banner notifications need a permission macOS may not have granted, and a
# plugin cannot detect delivery failure. They are therefore the *secondary*
# channel — the menubar title always shouts, and that needs no permission.
#   swiftbar  - SwiftBar's own banner    osascript - via Script Editor
#   both | none
NOTIFY_METHOD="both"

render_bar() { echo "$1"; echo "---"; shift; printf '%s\n' "$@"; exit 0; }
# Something is wrong and needs attention.
die() { render_bar "thermals ⚠️ | sfimage=thermometer.medium color=#ff6b6b" "$@"; }
# Working as intended, just not ready yet — must not look like a fault.
busy() { render_bar "thermals… | sfimage=thermometer.medium color=#8e8e93" "$@"; }

if [ "$(uname -m)" != "arm64" ]; then
  die "Apple Silicon only" "This plugin reads Apple Silicon SoC sensors, which Intel Macs do not expose."
fi

# --- build on first run -------------------------------------------------------
# Compiling takes a few seconds, and a plugin blocking the menubar that long
# looks like a hang. So the build is detached and the menubar says what it is
# doing; the next refresh picks up the finished binary.
age_of() { # file -> seconds since mtime, or a huge number if absent
  [ -f "$1" ] || { echo 999999; return; }
  echo $(( $(date +%s) - $(stat -f %m "$1" 2>/dev/null || echo 0) ))
}

if [ ! -x "$BIN" ]; then
  if ! command -v swiftc >/dev/null 2>&1; then
    die "Swift compiler not found" "mactemp needs the Command Line Tools." \
        "Install them | bash=/usr/bin/xcode-select param1=--install terminal=true"
  fi

  # A build already running: say so, unless the lock is stale.
  if [ -f "$BUILDING" ]; then
    if [ "$(age_of "$BUILDING")" -lt 300 ]; then
      busy "Building sensor reader…" "First run only. This takes a few seconds." \
          "Check again | refresh=true"
    fi
    rm -f "$BUILDING"
  fi

  # A recent failure: don't retry on every refresh.
  if [ -f "$FAILED" ] && [ "$(age_of "$FAILED")" -lt 600 ]; then
    die "Sensor reader failed to build" "Retrying is paused for 10 minutes." \
        "Show build log | bash=/bin/cat param1='$CACHE/build.log' terminal=true" \
        "Retry now | bash=/bin/rm param1='$FAILED' terminal=false refresh=true"
  fi

  cat > "$CACHE/mactemp.swift" <<'SWIFT_SOURCE_EOF'
@SWIFT_SOURCE@
SWIFT_SOURCE_EOF

  : > "$BUILDING"
  # Build to a temp name and move into place, so a half-written binary is never
  # executable. Stale builds from older versions are swept on success.
  nohup /bin/bash -c "
    if swiftc -O '$CACHE/mactemp.swift' -o '$BIN.tmp' > '$CACHE/build.log' 2>&1; then
      mv -f '$BIN.tmp' '$BIN'
      rm -f '$FAILED'
      find '$CACHE' -maxdepth 1 -name 'mactemp-*' ! -name 'mactemp-$SRC_HASH' -delete 2>/dev/null
    else
      rm -f '$BIN.tmp'
      touch '$FAILED'
    fi
    rm -f '$BUILDING'
  " >/dev/null 2>&1 &

  busy "Building sensor reader…" "First run only. This takes a few seconds." \
      "Check again | refresh=true"
fi

JSON="$("$BIN" 2>/dev/null)"
[ -z "$JSON" ] && die "No sensor data returned"

field() { echo "$JSON" | sed -n "s/.*\"$1\":\([0-9.]*\).*/\1/p"; }
DIE_MAX="$(field die_max)"
DIE_AVG="$(field die_avg)"
BATTERY="$(field battery)"
STORAGE="$(field storage)"
SENSORS="$(field sensors)"
STATE_NAME="$(echo "$JSON" | sed -n 's/.*"thermal_state":"\([a-z]*\)".*/\1/p')"

# --- sustained-pressure tracking ---------------------------------------------
PRESSURE_STREAK=0; BATTERY_STREAK=0; LAST_NOTIFY=0
# shellcheck disable=SC1090
[ -f "$STATE" ] && . "$STATE"

case "$STATE_NAME" in
  serious|critical) PRESSURE_STREAK=$((PRESSURE_STREAK + 1)) ;;
  *)                PRESSURE_STREAK=0 ;;
esac

if [ -n "$BATTERY" ] && [ "${BATTERY%.*}" -ge "$BATTERY_WARN" ] 2>/dev/null; then
  BATTERY_STREAK=$((BATTERY_STREAK + 1))
else
  BATTERY_STREAK=0
fi

NOW="$(date +%s)"
PLUGIN="$(basename "$0")"   # SwiftBar's plugin id is the full filename

notify() { # title, body
  local title="$1" body="$2"
  case "$NOTIFY_METHOD" in
    swiftbar|both)
      open "swiftbar://notify?plugin=${PLUGIN}&title=${title// /%20}&body=${body// /%20}" 2>/dev/null ;;
  esac
  case "$NOTIFY_METHOD" in
    osascript|both)
      osascript -e "display notification \"$body\" with title \"$title\"" >/dev/null 2>&1 ;;
  esac
  LAST_NOTIFY="$NOW"
}

if [ $((NOW - LAST_NOTIFY)) -ge "$NOTIFY_COOLDOWN" ]; then
  if [ "$PRESSURE_STREAK" -ge "$PRESSURE_SAMPLES" ]; then
    notify "Mac is throttling" "Sustained thermal pressure - expect things to feel slow. Check what is running."
  elif [ "$BATTERY_STREAK" -ge "$BATTERY_SAMPLES" ]; then
    notify "Battery is running hot" "${BATTERY}C sustained. Unplug or move it off soft surfaces."
  fi
fi

printf 'PRESSURE_STREAK=%s\nBATTERY_STREAK=%s\nLAST_NOTIFY=%s\n' \
  "$PRESSURE_STREAK" "$BATTERY_STREAK" "$LAST_NOTIFY" > "$STATE"

# --- render -------------------------------------------------------------------
case "$STATE_NAME" in
  nominal)  COLOR=""; ICON="thermometer.low";    PLAIN="Running free. No clocks are being held back." ;;
  fair)     COLOR=""; ICON="thermometer.medium"; PLAIN="Warm and working. Full speed, nothing to do." ;;
  serious)  COLOR="color=#ff9f0a"; ICON="thermometer.high"; PLAIN="Throttling. Speed is being clamped to shed heat." ;;
  critical) COLOR="color=#ff453a"; ICON="thermometer.high"; PLAIN="Heavily throttled. macOS is aggressively cutting speed." ;;
  *)        COLOR=""; ICON="thermometer.medium"; PLAIN="Thermal state unavailable." ;;
esac

# The always-works alert channel: once something has been wrong long enough to
# be worth saying, the menubar stops being a quiet number and says it in words.
LABEL="${DIE_MAX:+${DIE_MAX%.*}°}"
LABEL="${LABEL:-$STATE_NAME}"
if [ "$PRESSURE_STREAK" -ge "$PRESSURE_SAMPLES" ]; then
  echo "$LABEL throttling | sfimage=thermometer.high color=#ff453a"
elif [ "$BATTERY_STREAK" -ge "$BATTERY_SAMPLES" ]; then
  echo "$LABEL battery hot | sfimage=thermometer.high color=#ff9f0a"
else
  echo "$LABEL | sfimage=$ICON $COLOR"
fi
echo "---"
echo "Thermal pressure: ${STATE_NAME:-unknown} | sfimage=$ICON $COLOR"
echo "$PLAIN | size=11 color=#8e8e93"
echo "---"
if [ -n "$DIE_MAX" ]; then
  echo "SoC die (hottest)  ${DIE_MAX}°C | font=Menlo size=12"
  echo "SoC die (average)  ${DIE_AVG}°C | font=Menlo size=12"
else
  echo "No SoC die sensors exposed on this Mac | size=11 color=#8e8e93"
fi
[ -n "$STORAGE" ] && echo "SSD                ${STORAGE}°C | font=Menlo size=12"
if [ -n "$BATTERY" ]; then
  BCOL=""
  [ "${BATTERY%.*}" -ge "$BATTERY_WARN" ] 2>/dev/null && BCOL="color=#ff9f0a"
  echo "Battery            ${BATTERY}°C | font=Menlo size=12 $BCOL"
fi
echo "---"
echo "Top CPU right now"
ps -Ao %cpu,comm -r 2>/dev/null | sed -n '2,4p' | while read -r pct cmd; do
  echo "$(printf '%5s%%' "$pct")  $(basename "$cmd") | font=Menlo size=12"
done
echo "---"
echo "Open Activity Monitor | bash=/usr/bin/open param1=-a param2='Activity Monitor' terminal=false"
echo "All ${SENSORS:-0} sensors | bash='$BIN' param1=--list terminal=true"
echo "Refresh | refresh=true"
